services:
  spark:
    image: "quay.io/jupyter/pyspark-notebook"
    ports:
      - "8888:8888"  # Jupyter Server
      - "4040:4040"  # Spark Jobs (monitoring)
      - "18080:18080"
    volumes:
      - ./data:/home/jovyan/data
      - ./report/img:/home/jovyan/output
      - ./src:/home/jovyan/src
